### ISSUE TITLE
Untie from Immutable

### ISSUE THREAD

**Issue by StreetStrider** [ThomWright/flyd-cacheUntil#2]
Hello. Would you considering to change this module to return native Array instead of Immutable's type? I presume you use it as a matter of preference, but when you develop such basic module you need to be lib-agnostic. I think it is possible to keep both APIs: native Array API and Immutable in this manner:

``` js
require('flyd-cacheUntil') // when invoked this returns native Array
require('flyd-cacheUntil/immutable') // this returns Immutable List
```

**Comment by ThomWright** [comment]
Agreed!

I was just playing around when I made this.

**Comment by StreetStrider** [comment]
Great, thank you.
